print_info() {
    prin "\n"
    info "$(color 5) ╭─" distro
    info "$(color 5) ├─" kernel
    info "$(color 5) ├─" users
    info "$(color 5) ├─󰏗" packages
    info "$(color 5) ╰─" shell
    info "$(color 4) ╭─" de
    info "$(color 4) ├─" resolution
    info "$(color 4) ├─" memory
    info "$(color 4) ├─" disk
    info "$(color 4) ├─" term
    info "$(color 4) ╰─󰄉" uptime
    prin "\n"
    prin "$(color 0)⬤ $(color 7)⬤ $(color 6)⬤ $(color 5)⬤ $(color 4)⬤ $(color 3)⬤ $(color 2)⬤ $(color 1)⬤"
    prin "\n"
}
